version: "3"
services:
  api-gateway:
    build:
      context: ./
      dockerfile: ./backend-app/api-gateway/dockerfile
    container_name: api-gateway
    hostname: api-gateway
    ports:
      - 8443:8443
    environment:
      - DIPLOMA_PASSWORD
    networks:
      - bg-network
  discovery-server:
    build:
      context: ./
      dockerfile: ./backend-app/discovery-server/dockerfile
    container_name: discovery-server
    ports:
      - 8761:8761
    hostname: discovery-server
    networks:
      - bg-network
    environment:
      - DIPLOMA_PASSWORD
  account-service:
    build:
      context: ./
      dockerfile: ./backend-app/micro-services/account-service/dockerfile
    container_name: account-service
    ports:
      - 9001:9001
      - 9901:9901
      - 5051:5051
    hostname: account-service
    networks:
      - bg-network
    environment:
      - DIPLOMA_PASSWORD
    depends_on:
      - db
      - discovery-server
  shop-service:
    build:
      context: ./
      dockerfile: ./backend-app/micro-services/shop-service/dockerfile
    container_name: shop-service
    ports:
      - 9002:9002
      - 9902:9902
      - 5052:5052
    hostname: account-service
    networks:
      - bg-network
    environment:
      - DIPLOMA_PASSWORD
      - CRYPTO_SEED=123123
    depends_on:
      - db
      - discovery-server
  db:
    build:
      context: ./
      dockerfile: ./database/dockerfile
    ports:
      - 5433:5432
    hostname: db
    networks:
      - bg-network
    container_name: db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=admin
      - POSTGRES_DB=BOARDGAMES_SHOP
    volumes:
    - boardgames_db:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: BOARDGAMES_SHOP
      DB_USER: admin
      DB_SCHEMA: auth
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_FRONTEND_URL: https://localhost:8443/auth
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    container_name: keycloak
    ports:
      - 9990:8080
      - 9991:8443
    hostname: keycloak
    networks:
      - bg-network
    volumes:
      - type: bind
        source: ./keycloak/src/main/resources/realm-export.json
        target: /tmp/realm-export.json
    depends_on:
      - db
    command: -Dkeycloak.profile.feature.upload_scripts=enabled

volumes:
  boardgames_db:
    name: boardgames_db
networks:
  bg-network:
    name: network
