spring:
  application:
    name: api-gateway


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: api-gateway
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}

server:
  port: 8443
  ssl:
    key-password: ${DIPLOMA_PASSWORD}
    key-store-password: ${DIPLOMA_PASSWORD}
    key-store: ./keystore.jks
    enabled-protocols: TLSv1.2



zuul:
  ribbon:
    eager-load:
      enabled: true
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    account-service:
      path: /account/**
      serviceId: account-service
      stripPrefix: true
    shop-service:
      path: /shop/**
      serviceId: shop-service
      stripPrefix: true
    inventory-service:
      path: /inventory/**
      serviceId: inventory-service
      stripPrefix: true
    authorization-server:
      sensitiveHeaders:
      path: /auth/**
      url: http://keycloak:8080
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2400000
          strategy: THREAD

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000

