FROM openjdk:8-jre-alpine
MAINTAINER Jakub Fornalski
WORKDIR /app
COPY ./discovery-service/target/discovery-service.jar /app/
COPY ./keystore.jks /app/
ENTRYPOINT ["java", "-jar", "discovery-service.jar"]

