FROM openjdk:8-jre-alpine
MAINTAINER Jakub Fornalski
WORKDIR /app
COPY /target/discovery-service.jar /app/
COPY /src/main/resources/keystore.jks /app/
ENTRYPOINT ["java", "-jar", "discovery-service.jar"]

