eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: account-service

spring:
  application:
    name: account-service
server:
  port: 9001

management:
  server:
    port: 9901
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

keycloak:
  auth-server-url: http://keycloak:8080/auth
  realm: board-game-parts-shop
  resource: account-service
  bearer-only: true
  principal-attribute: preferred_username

#server.ssl.key-password=${DIPLOMA_PASSWORD}
#server.ssl.key-store-password=${DIPLOMA_PASSWORD}
#server.ssl.key-store=./keystore.jks